[package]
name = "proxy-api"
version = "0.1.1"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
lazy_static = "1.4.0"
dotenv = "0.15.0"
hyper-tls = "0.5.0"